In [5]:
import requests
from requests.auth import HTTPBasicAuth
import urllib3
import json
import pandas as pd

# 경고 끄기
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def load_api(url, save_data=False):  
    # 기본 설정
    username = 'csdtpcp'       # 아이디
    password = 'dtpcp!@'       # 비밀번호
    # 요청 보내기
    response = requests.get(url, auth=HTTPBasicAuth(username, password), verify=False)

    # 응답 확인
    if response.status_code == 200:
        data = response.json()  # JSON 형식으로 파싱
        if save_data:
            # JSON 파일로 저장
            with open('output.json', 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=4)
    else:
        print(f'접근 실패: 상태 코드 {response.status_code}')
        return False       
    return data

In [6]:
project_id = 'e672bd1e-5ed0-4baa-9cbd-50db20ea24db'

In [38]:
data_all_process = load_api('https://corners.synology.me:30006/woojin-dev490/ProcCat/447477ef-0986-4d2a-80f5-69d445b8a803')
df_all_process = pd.DataFrame(data_all_process['data'])
df_all_process

,pcId,upPcId,siteId,pcLevel,pcSeq,pcNm,pcCd,desc1
0,ee9d0398-8fae-48e4-b1a8-dbdc4029b4da,None,447477ef-0986-4d2a-80f5-69d445b8a803,1,1,차체,PROC0001,차체 대분류
1,d74ea2d0-477c-4834-a610-172e766cc33a,None,447477ef-0986-4d2a-80f5-69d445b8a803,1,2,차체 운송,PROC0020,차체 운송 대분류
2,e39ff221-f1d2-48b7-901a-4e3f279fbcef,None,447477ef-0986-4d2a-80f5-69d445b8a803,1,5000,도장,PROC0002,도장
3,6916e757-6569-4fad-ad78-569c90e016ea,None,447477ef-0986-4d2a-80f5-69d445b8a803,1,5001,도장 운송,PROC0020,도장운송 대분류
4,43dc4be4-2330-4e3a-8fef-84ec188a094a,None,447477ef-0986-4d2a-80f5-69d445b8a803,1,10000,선행의장,PROC0003,선행 의장
...,...,...,...,...,...,...,...,...
202,118546fb-155d-4fd4-b716-334ac5602428,64af7702-2d7a-44c1-8325-ca25acc93516,447477ef-0986-4d2a-80f5-69d445b8a803,3,20101,대차차입 전 검사 / 대차 차입,PROC0005,None
203,8a67c4be-49c7-4cb5-a5e0-8ac51ec40122,64af7702-2d7a-44c1-8325-ca25acc93516,447477ef-0986-4d2a-80f5-69d445b8a803,3,20102,대차 결선,PROC0005,None
204,052160b2-51dc-42ef-aa56-bc7c4f472bfa,64af7702-2d7a-44c1-8325-ca25acc93516,447477ef-0986-4d2a-80f5-69d445b8a803,3,20103,접지선 결선,PROC0005,None
205,2a2f3901-14cb-45b4-b17a-d12a569790ea,64af7702-2d7a-44c1-8325-ca25acc93516,447477ef-0986-4d2a-80f5-69d445b8a803,3,20201,대차측 전장품 취부 결선 & 마무리작업,PROC0005,None
206,cfae0823-3d36-4f38-a902-619beca12b22,64af7702-2d7a-44c1-8325-ca25acc93516,447477ef-0986-4d2a-80f5-69d445b8a803,3,20301,대차차입 후 검사,PROC0005,None

In [39]:
count = 0
for i in range(len(data_all_process['data'])):
    # if data_process_category['data'][i]['pcCd'] in ['PROC0003', 'PROC0004', 'PROC0005']:
    if data_all_process['data'][i]['pcCd'] in ['PROC0004'] and data_all_process['data'][i]['pcLevel'] == 3:
    # if data_process_category['data'][i]['pcCd'] in ['PROC0004'] and data_process_category['data'][i]['pcLevel'] == 3:
        print(i, data_all_process['data'][i]['pcNm'])
        count += 1
        # print(i, data_process_category['data'][i])

129 흡음재 취부
130 흡음재 씰링/검사/수정
131 T-BOLT 취부
132 배기팬 커버 취부
133 전장품 취부 및 고압 배선 압착작업
134 내전압 검사 (상,하 전기)
135 실내 배선
136 실내 입선 검사
137 일반 배전반 취부
138 냉난방 배전반 배선 및 컨넥트 작업
139 운전실 1차 배선 작업
140 운전실 2차 배선작업 및 기기류 컨넥트 작업
141 실내/상하 CABLE HARNESS 취부
142 실내/상하 배선
143 D+1~4일차 조정작업
144 실내/상하 입선 검사/수정
145 리무벌프레임 취부
146 AIR DUCT MODULE 취부
147 측창취부
148 STOP PLATE & 센터그릴 취부
149 파티션 프레임 취부
150 LINE FLOW FAN 취부 결선
151 AIR DUCT MODULE 취부 검사
152 CAB MODULE 취부
153 AIR CON 취부
154 ROOF 내장판 취부
155 운전실 내장판/캐비넷 취부
156 배관 MODULE 취부
157 객실 도어 취부
158 일반,냉난방 배전반 취부 결선
159 옥상기기 취부 결선
160 상하 전장기기 취부 결선
161 CENTER PIVOT 취부
162 도통 검사
163 부적합수정
164 COUPLER 취부
165 도통입회검사/내전압자체검사
166 제동기기 취부 및 누설검사
167 SIDE 내장판 취부
168 내전압 입회검사
169 코너씰링
170 D+5~16일차 조정작업
171 내장판 조정작업
172 객실도어 취부 검사
173 운전실 배전반 취부 결선
174 내장판 취부 검사
175 운전실 DOOR 취부
176 핸드레일 취부
177 시트프레임 취부
178 운전실 전장기기 취부 결선
179 실내/운전실 설비 완료
180 도어 조정 및 비상핸들 취부
181 실내 전장품 취부 결선
182 실외 설비품/DIAPHRAGM 취부
183 전장기기 취부 결선 완료
184 드라프트 스크린 취부
185 실외 전장품 취부 결선
186 스텐션폴 취부
187 도통 자체 검사 (TC-Car)
188 핸드스트랩 취부
189 D+17~20일차 조정작업
190 도통 검사 수정 (TC-Car)
191 선반 취부
192 내전압 입회 검사 (TC-Car)
193 형광등 취부
194 도통 검사 (TC-Car)
195 장애인 설비, 기타 설비 취부
196 전장취부 결선 복구
197 실내 조정 및 실내·외 설비 완료
198 전장품 취부 입회검사
199 수정작업 및 점검커버 복구 (전기)
200 수정작업 및 점검커버 복구 (의장)
201 실내 설비 입회검사

In [40]:
count

73

In [41]:
load_api('https://corners.synology.me:30006/woojin-dev490/Processes/Seq?pcCd=PROC0004')

{'code': 0,
 'message': 'SUCCESS',
 'data': [{'pcDaySeq': 1,
   'pcId': '8718b46d-cf23-4b2f-959c-c1a63f9532b6',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '흡음재 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 2,
   'pcId': 'c30eb0bd-a767-409a-a968-75aa0757bfb0',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '흡음재 씰링/검사/수정',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 3,
   'pcId': 'f3b9bd9d-eba6-4fa5-98fb-3202fe0b5f1b',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '실내/상하 CABLE HARNESS 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 4,
   'pcId': '803d1d3c-6efd-4a42-bfbf-cccb4868bbfd',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '실내/상하 배선',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 5,
   'pcId': 'e0471187-5ee5-4fed-8383-c102704e26df',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': 'D+1~4일차 조정작업',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 6,
   'pcId': '51eab8d3-38d2-453b-962e-6f16e0ffa081',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '리무벌프레임 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 6,
   'pcId': '0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '실내/상하 입선 검사/수정',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 7,
   'pcId': 'b1d76e32-b363-49ed-9d1e-df5fe4699ed1',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': 'AIR DUCT MODULE 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 8,
   'pcId': '93d2cc2b-a71f-40c0-ae8d-0d2af8885f9c',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '측창취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 8,
   'pcId': '3f69f52d-c206-43a5-abd1-d47eb8e8aabf',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': 'LINE FLOW FAN 취부 결선',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 8,
   'pcId': '612897d8-78df-4b88-bcc0-b4e1d942a1c2',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': 'STOP PLATE & 센터그릴 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 9,
   'pcId': '04dbb438-9874-4cb3-ba23-48dba6b6aab7',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': 'CAB MODULE 취부',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 9,
   'pcId': 'f1441ccb-398b-46fd-b9e8-128c5fa49bb2',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': 'AIR DUCT MODULE 취부 검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 9,
   'pcId': '19eade95-30e7-41f4-ba1f-e09e09614c4a',
   'pcTp': 3,
   'pcCd': 'PROC0004',
   'pcNm': 'AIR CON 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 10,
   'pcId': '239fddf2-c250-4761-a14f-2a941a9fda75',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': 'ROOF 내장판 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 10,
   'pcId': 'fdb5af99-eac4-4ece-9f42-0c6639fdce5c',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '운전실 내장판/캐비넷 취부',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 11,
   'pcId': '7dac19ab-a4d8-431f-95a9-199e3dbaa684',
   'pcTp': 3,
   'pcCd': 'PROC0004',
   'pcNm': '배관 MODULE 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 11,
   'pcId': '6b0dcc6c-9fea-42c5-947c-6815ba40370b',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '객실 도어 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 12,
   'pcId': '406990fb-253f-4b65-a7db-c7e50f6775cb',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '객실도어 취부 검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 13,
   'pcId': '27f617fd-d1b3-4175-bb84-f24c848d3090',
   'pcTp': 3,
   'pcCd': 'PROC0004',
   'pcNm': 'CENTER PIVOT 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 13,
   'pcId': 'ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '일반,냉난방 배전반 취부 결선',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 14,
   'pcId': 'aa77dbb8-fa64-403f-9e40-f4a1b398b7bf',
   'pcTp': 3,
   'pcCd': 'PROC0004',
   'pcNm': '제동기기 취부 및 누설검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'Y'},
  {'pcDaySeq': 14,
   'pcId': 'fce31937-b674-4400-8ceb-776864a641ed',
   'pcTp': 3,
   'pcCd': 'PROC0004',
   'pcNm': 'COUPLER 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 15,
   'pcId': 'afcd8387-dc68-4d2e-8068-d1e01e619e89',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': 'SIDE 내장판 취부',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 16,
   'pcId': 'ffe4e06d-cc13-472c-9bbf-7aceb852c0af',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '상하 전장기기 취부 결선',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 16,
   'pcId': '2f14336a-38e5-4650-ab56-b8045fac5be0',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '옥상기기 취부 결선',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 17,
   'pcId': '3d3a7a3e-2326-40e5-b810-e98df91b745d',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '도통 검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 18,
   'pcId': '9184fc1e-f9f5-4dd6-b2f5-e942b9613b27',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '도통입회검사/내전압자체검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 18,
   'pcId': '127fdb1e-97fd-4525-a4c2-05dd123dff8b',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '부적합수정',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 19,
   'pcId': '95b44996-4c78-4d27-808c-8c457ce76be8',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '내전압 입회검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 20,
   'pcId': '30238e8d-aa85-40d0-b621-578ed1d9bd00',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': 'D+5~16일차 조정작업',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 21,
   'pcId': '67114600-1c26-4313-941b-10c2e4d6a1ff',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '운전실 배전반 취부 결선',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 22,
   'pcId': 'c49e416e-39de-48d6-815a-4ee0e734015b',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '운전실 DOOR 취부',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 23,
   'pcId': '0a1ebad7-306b-4f6d-87f1-6adb7bc1d0cd',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '운전실 전장기기 취부 결선',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 23,
   'pcId': '002cfaa5-4bf1-4325-9d54-281b9e4f439e',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '내장판 조정작업(완료)',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 24,
   'pcId': 'd1e83483-4e9b-4b1a-beba-9a8994d06528',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '내장판 취부 검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 25,
   'pcId': '59043214-e767-4ba2-8992-754b68dfebea',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '전장기기 취부 결선 완료',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 25,
   'pcId': '347041ed-ed49-4175-8391-6dd284b4e637',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '도통 자체 검사 (TC-Car)',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 26,
   'pcId': '7a21a47f-fea2-4c33-a991-c9fbe85eec90',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '도통 검사 수정 (TC-Car)',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 27,
   'pcId': '07cda3b6-bee6-4b16-a2fa-3a6b02a50689',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '전장취부 결선 복구',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 27,
   'pcId': '9a6519e5-8bd2-443e-8bd0-e3787716fe7d',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '실내조정 및 Sealing',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 27,
   'pcId': '9cda7382-f0bd-4b0a-908d-82d5c83fb0c4',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '도통,내전압 검사 (TC-Car)',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 28,
   'pcId': 'f12e681f-1f2a-46b1-819c-c22d580a0a3b',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': 'D+17~20일차 조정작업',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 28,
   'pcId': 'ef4ef3c1-5598-4f99-bd0d-b45bf186a3aa',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '내전압 입회 검사 (TC-Car)',
   'tcCheck': 1,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 29,
   'pcId': 'b6cd7eb1-2faa-4127-a457-8744facf75d7',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '전장품 취부 입회검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'N'},
  {'pcDaySeq': 29,
   'pcId': '1e3ab08b-af38-4c6a-9873-9fbf37f51e6c',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '수정작업 및 점검커버 복구 (의장)',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'},
  {'pcDaySeq': 29,
   'pcId': 'f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e',
   'pcTp': 1,
   'pcCd': 'PROC0004',
   'pcNm': '실내 설비 입회검사',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 1,
   'lastPcYn': 'Y'},
  {'pcDaySeq': 29,
   'pcId': '793cf042-2a6d-409b-a7a6-38cca3701aa0',
   'pcTp': 2,
   'pcCd': 'PROC0004',
   'pcNm': '수정작업 및 점검커버 복구 (전기)',
   'tcCheck': 0,
   'm1Check': 0,
   'examCheck': 0,
   'lastPcYn': 'N'}]}

In [42]:
data_proc4 = load_api('https://corners.synology.me:30006/woojin-dev490/Processes/Seq?pcCd=PROC0004')
df_proc4 = pd.DataFrame(data_proc4['data'])
df_proc4

,pcDaySeq,pcId,pcTp,pcCd,pcNm,tcCheck,m1Check,examCheck,lastPcYn
0,1,8718b46d-cf23-4b2f-959c-c1a63f9532b6,1,PROC0004,흡음재 취부,0,0,0,N
1,2,c30eb0bd-a767-409a-a968-75aa0757bfb0,1,PROC0004,흡음재 씰링/검사/수정,0,0,1,N
2,3,f3b9bd9d-eba6-4fa5-98fb-3202fe0b5f1b,2,PROC0004,실내/상하 CABLE HARNESS 취부,0,0,0,N
3,4,803d1d3c-6efd-4a42-bfbf-cccb4868bbfd,2,PROC0004,실내/상하 배선,0,0,0,N
4,5,e0471187-5ee5-4fed-8383-c102704e26df,2,PROC0004,D+1~4일차 조정작업,0,0,1,N
5,6,51eab8d3-38d2-453b-962e-6f16e0ffa081,1,PROC0004,리무벌프레임 취부,0,0,0,N
6,6,0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727,2,PROC0004,실내/상하 입선 검사/수정,0,0,1,N
7,7,b1d76e32-b363-49ed-9d1e-df5fe4699ed1,1,PROC0004,AIR DUCT MODULE 취부,0,0,0,N
8,8,93d2cc2b-a71f-40c0-ae8d-0d2af8885f9c,1,PROC0004,측창취부,0,0,0,N
9,8,3f69f52d-c206-43a5-abd1-d47eb8e8aabf,2,PROC0004,LINE FLOW FAN 취부 결선,0,0,0,N
10,8,612897d8-78df-4b88-bcc0-b4e1d942a1c2,1,PROC0004,STOP PLATE & 센터그릴 취부,0,0,0,N
11,9,04dbb438-9874-4cb3-ba23-48dba6b6aab7,1,PROC0004,CAB MODULE 취부,1,0,0,N
12,9,f1441ccb-398b-46fd-b9e8-128c5fa49bb2,1,PROC0004,AIR DUCT MODULE 취부 검사,0,0,1,N
13,9,19eade95-30e7-41f4-ba1f-e09e09614c4a,3,PROC0004,AIR CON 취부,0,0,0,N
14,10,239fddf2-c250-4761-a14f-2a941a9fda75,1,PROC0004,ROOF 내장판 취부,0,0,0,N
15,10,fdb5af99-eac4-4ece-9f42-0c6639fdce5c,1,PROC0004,운전실 내장판/캐비넷 취부,1,0,0,N
16,11,7dac19ab-a4d8-431f-95a9-199e3dbaa684,3,PROC0004,배관 MODULE 취부,0,0,0,N
17,11,6b0dcc6c-9fea-42c5-947c-6815ba40370b,1,PROC0004,객실 도어 취부,0,0,0,N
18,12,406990fb-253f-4b65-a7db-c7e50f6775cb,1,PROC0004,객실도어 취부 검사,0,0,1,N
19,13,27f617fd-d1b3-4175-bb84-f24c848d3090,3,PROC0004,CENTER PIVOT 취부,0,0,0,N
20,13,ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e,2,PROC0004,"일반,냉난방 배전반 취부 결선",0,0,0,N
21,14,aa77dbb8-fa64-403f-9e40-f4a1b398b7bf,3,PROC0004,제동기기 취부 및 누설검사,0,0,1,Y
22,14,fce31937-b674-4400-8ceb-776864a641ed,3,PROC0004,COUPLER 취부,0,0,0,N
23,15,afcd8387-dc68-4d2e-8068-d1e01e619e89,1,PROC0004,SIDE 내장판 취부,0,0,0,N
24,16,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2,PROC0004,상하 전장기기 취부 결선,0,0,0,N
25,16,2f14336a-38e5-4650-ab56-b8045fac5be0,2,PROC0004,옥상기기 취부 결선,0,0,0,N
26,17,3d3a7a3e-2326-40e5-b810-e98df91b745d,2,PROC0004,도통 검사,0,0,1,N
27,18,9184fc1e-f9f5-4dd6-b2f5-e942b9613b27,2,PROC0004,도통입회검사/내전압자체검사,0,0,1,N
28,18,127fdb1e-97fd-4525-a4c2-05dd123dff8b,2,PROC0004,부적합수정,0,0,0,N
29,19,95b44996-4c78-4d27-808c-8c457ce76be8,2,PROC0004,내전압 입회검사,0,0,1,N
30,20,30238e8d-aa85-40d0-b621-578ed1d9bd00,2,PROC0004,D+5~16일차 조정작업,0,0,1,N
31,21,67114600-1c26-4313-941b-10c2e4d6a1ff,2,PROC0004,운전실 배전반 취부 결선,1,0,0,N
32,22,c49e416e-39de-48d6-815a-4ee0e734015b,1,PROC0004,운전실 DOOR 취부,1,0,0,N
33,23,0a1ebad7-306b-4f6d-87f1-6adb7bc1d0cd,2,PROC0004,운전실 전장기기 취부 결선,1,0,0,N
34,23,002cfaa5-4bf1-4325-9d54-281b9e4f439e,1,PROC0004,내장판 조정작업(완료),0,0,0,N
35,24,d1e83483-4e9b-4b1a-beba-9a8994d06528,1,PROC0004,내장판 취부 검사,0,0,1,N
36,25,59043214-e767-4ba2-8992-754b68dfebea,2,PROC0004,전장기기 취부 결선 완료,0,0,0,N
37,25,347041ed-ed49-4175-8391-6dd284b4e637,2,PROC0004,도통 자체 검사 (TC-Car),1,0,0,N
38,26,7a21a47f-fea2-4c33-a991-c9fbe85eec90,2,PROC0004,도통 검사 수정 (TC-Car),1,0,0,N
39,27,07cda3b6-bee6-4b16-a2fa-3a6b02a50689,2,PROC0004,전장취부 결선 복구,0,0,0,N
40,27,9a6519e5-8bd2-443e-8bd0-e3787716fe7d,1,PROC0004,실내조정 및 Sealing,0,0,0,N
41,27,9cda7382-f0bd-4b0a-908d-82d5c83fb0c4,2,PROC0004,"도통,내전압 검사 (TC-Car)",1,0,1,N
42,28,f12e681f-1f2a-46b1-819c-c22d580a0a3b,2,PROC0004,D+17~20일차 조정작업,0,0,1,N
43,28,ef4ef3c1-5598-4f99-bd0d-b45bf186a3aa,2,PROC0004,내전압 입회 검사 (TC-Car),1,0,0,N
44,29,b6cd7eb1-2faa-4127-a457-8744facf75d7,2,PROC0004,전장품 취부 입회검사,0,0,1,N
45,29,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,1,PROC0004,수정작업 및 점검커버 복구 (의장),0,0,0,N
46,29,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,1,PROC0004,실내 설비 입회검사,0,0,1,Y
47,29,793cf042-2a6d-409b-a7a6-38cca3701aa0,2,PROC0004,수정작업 및 점검커버 복구 (전기),0,0,0,N

In [43]:
data_process_seq = load_api('https://corners.synology.me:30006/woojin-dev490/Processes/Seq/' + project_id)
df_process_seq = pd.DataFrame(data_process_seq['data'])
df_process_seq

,procSeq,procId,pcId,pcNm,wt,projId,projNm,transYn,desc1,useTc,useT,useM,useEtc,wtTc,wtT,wtM,wtEtc,workGroups,examYn
0,100,229dfa72-6ad3-4c31-8104-0129e9f50152,c95df008-e3f6-4d55-9325-8e76da5fc734,UNDER PANEL 조립 & 검사 & 자동용접,600,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,N,PROC0001 차체01 UNDER PANEL 조립 & 검사,Y,Y,Y,Y,600,600,600,600,None,N
1,300,f7595b1b-b265-4d0b-b8bd-f86ec8ac1f14,d8cae93e-2ffb-4671-bd01-0428fafac15c,운송 차제2->차체3,14,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,Y,PROC0020 차체 운송 운송 차제2->차체3,Y,Y,Y,Y,14,14,14,14,None,N
2,400,539d8f54-818d-49c0-ad52-ba3925691358,f699b89c-1a78-4619-89d3-c4e61dfc1123,UNDER PANEL 교정,300,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,N,PROC0001 차체03 UNDER PANEL 교정,Y,Y,Y,Y,300,300,300,300,None,N
3,500,fca5166d-c0ac-4851-8ae2-6e0b22f6bdd4,6bc11d3e-0474-496c-8695-bb7a10a6b963,운송 차제3->차체4,18,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,Y,PROC0020 차체 운송 운송 차제3->차체4,Y,Y,Y,Y,18,18,18,18,None,N
4,600,6ba90330-ca7a-4d46-9099-88516c8b552b,8fd9915f-40b7-40f6-9c5f-b8b09dc0637b,UNDER PANEL 가공,600,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,N,PROC0001 차체04 UNDER PANEL 가공,Y,Y,Y,Y,600,600,600,600,None,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,18000,24921591-8ec7-47d4-92b9-fa240099db72,26ac3069-9063-41c6-815e-5e5f45e15b6f,실외설비품 & 소화기 취부,420,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,N,PROC0004 의장정지점08 실외설비품 & 소화기 취부,Y,Y,Y,Y,420,360,360,420,None,N
106,18100,8c0cbd86-362e-4ede-9e41-5ede39c654c5,9edc7ea7-e9c9-4e2d-91c8-a0f69f9a3b40,실내설비/전장품 취부검사,5280,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,N,"PROC0004 의장정지점08 실내 설비, 전장품 취부검사",Y,Y,Y,Y,60,60,60,60,None,Y
107,18101,bbd0af44-87a9-41a8-8c33-829797623d21,5e4eb94d-7980-4dee-81a8-f06fe847bc73,운송 본의장 -> 완성 의장,34,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,Y,PROC0020 본의장 운송 운송 본의장 -> 완성 의장,Y,Y,Y,Y,34,34,34,34,None,N
108,20100,0f9c5582-b3be-4cf4-bc09-028ea6396614,64af7702-2d7a-44c1-8325-ca25acc93516,대차 차입 및 배관 마무리작업,480,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,N,PROC0005 대차 배관 마무리작업,Y,Y,Y,Y,480,480,480,480,None,N
109,20301,451bd1b1-d106-4b6d-8d1b-9a44f8640ea5,1e2fea59-e4f1-4a18-a452-7b33a7066992,운송 의장 -> 완료검사,3,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,서울지하철공사 57호선 336량,Y,PROC0020 대차 운송 운송 의장 -> 완료검사,Y,Y,Y,Y,3,3,3,3,None,N

In [44]:
df_process_seq[df_process_seq['pcId'].isin(df_proc4['pcId'])]

Empty DataFrame
Columns: [procSeq, procId, pcId, pcNm, wt, projId, projNm, transYn, desc1, useTc, useT, useM, useEtc, wtTc, wtT, wtM, wtEtc, workGroups, examYn]
Index: []

In [7]:
data_all_cars = load_api('https://corners.synology.me:30006/woojin-dev490/Cars/' + project_id + '?allYn=N')
df_all_cars = pd.DataFrame(data_all_cars['data'])
df_all_cars

,carId,projId,carSeq,carType,carCd,carPairNo,lineNo,progress,latency,totalTime,...,useNextYn,planCarYn,prevPlanDate,firstPlanDate,firstChkDay,lastPlanDate,lastPcId,lastChkDay,carNo,carSeqS
0,eaf6f703-18c4-4d64-9d96-09cbe521b98d,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1,TC1,001-TC1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,001,1
1,fcdd791d-d9ce-4191-9451-9738c13d9978,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2,M1,002-M1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,002,2
2,9462c71b-52aa-4df6-84b4-a8fcbf2094fb,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3,M2,003-M2-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,003,3
3,907a3d1d-1ec6-4e05-9129-aec5082aa9d3,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,4,TC2,008-TC2-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,008,4
4,8eae2965-e109-49c8-8e2e-bcd38d5d579f,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,5,T1,004-T1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,004,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,68134945-224e-4ba8-96ec-0335e940aa13,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,300,M2,299-M2-75,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,299,300
332,3d6fae33-bef3-4a62-970c-df564d3a1087,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,301,T2,301-T2-38,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,301,301
333,675993ce-07bc-4eb7-94c7-2732d432be49,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,302,M1,302-M1-76,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,302,302
334,5281ee51-27d4-4f8f-85bf-2ba5e1b7d995,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,303,TC2,304-TC2-38,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,304,303
335,50f3de2c-23d4-4b3f-a639-c76fbd639a32,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,304,M2,303-M2-76,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,303,304

In [46]:
df_all_cars['carId'][0]

'eaf6f703-18c4-4d64-9d96-09cbe521b98d'

In [47]:
data_car = load_api('https://corners.synology.me:30006/woojin-dev490/WorkPlan/' + project_id + '/' + df_all_cars['carId'][0])
data_car

{'code': 10, 'message': 'NO DATA', 'data': None}

In [48]:
data_car2 = load_api('https://corners.synology.me:30006/woojin-dev490/WorkPlan/' + project_id + '/' + df_all_cars['carId'][50])
df_car2 = pd.DataFrame(data_car2['data'])
df_car2

,projId,pcId,planDate,pcnt,cno1,cno2,cno3,pcNm
0,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f1441ccb-398b-46fd-b9e8-128c5fa49bb2,2021-04-08,67,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,AIR DUCT MODULE 취부 검사
1,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,002cfaa5-4bf1-4325-9d54-281b9e4f439e,2021-05-06,67,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,내장판 조정작업
2,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,d1e83483-4e9b-4b1a-beba-9a8994d06528,2021-05-07,67,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,내장판 취부 검사
3,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,95b44996-4c78-4d27-808c-8c457ce76be8,2021-05-21,62,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,내전압 입회검사
4,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,9cda7382-f0bd-4b0a-908d-82d5c83fb0c4,2021-05-21,62,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,도통 검사 (TC-Car)
5,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3d3a7a3e-2326-40e5-b810-e98df91b745d,2021-05-21,62,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,도통 검사
6,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,5f00c772-1919-4f2e-b207-7800abfebf66,2021-05-21,62,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,None
7,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b6cd7eb1-2faa-4127-a457-8744facf75d7,2021-05-24,64,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,전장품 취부 입회검사
8,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,64af7702-2d7a-44c1-8325-ca25acc93516,2021-05-24,64,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,None
9,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,2021-05-24,64,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,실내 설비 입회검사
10,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,9184fc1e-f9f5-4dd6-b2f5-e942b9613b27,2021-05-24,64,92bc72b3-61f0-4b05-8d72-eea3a80afb55,None,None,도통입회검사/내전압자체검사

In [49]:
len(data_car2['data'])

11

In [50]:
data_car2['data'][0]['pcId'] in list(df_process_seq['pcId'])

False

In [51]:
data_car2['data'][0]['pcId'] in list(df_proc4['pcId'])

True

In [52]:
df_all_cars[df_all_cars['carId']=='aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7']

,carId,projId,carSeq,carType,carCd,carPairNo,lineNo,progress,latency,totalTime,...,useNextYn,planCarYn,prevPlanDate,firstPlanDate,firstChkDay,lastPlanDate,lastPcId,lastChkDay,carNo,carSeqS
102,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,167,M2,167-M2-42,513,5,100,0,43022,...,None,None,None,None,None,None,None,None,167,167

In [53]:
df_all_cars

,carId,projId,carSeq,carType,carCd,carPairNo,lineNo,progress,latency,totalTime,...,useNextYn,planCarYn,prevPlanDate,firstPlanDate,firstChkDay,lastPlanDate,lastPcId,lastChkDay,carNo,carSeqS
0,eaf6f703-18c4-4d64-9d96-09cbe521b98d,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1,TC1,001-TC1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,001,1
1,fcdd791d-d9ce-4191-9451-9738c13d9978,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2,M1,002-M1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,002,2
2,9462c71b-52aa-4df6-84b4-a8fcbf2094fb,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3,M2,003-M2-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,003,3
3,907a3d1d-1ec6-4e05-9129-aec5082aa9d3,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,4,TC2,008-TC2-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,008,4
4,8eae2965-e109-49c8-8e2e-bcd38d5d579f,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,5,T1,004-T1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,004,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,68134945-224e-4ba8-96ec-0335e940aa13,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,300,M2,299-M2-75,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,299,300
332,3d6fae33-bef3-4a62-970c-df564d3a1087,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,301,T2,301-T2-38,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,301,301
333,675993ce-07bc-4eb7-94c7-2732d432be49,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,302,M1,302-M1-76,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,302,302
334,5281ee51-27d4-4f8f-85bf-2ba5e1b7d995,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,303,TC2,304-TC2-38,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,304,303
335,50f3de2c-23d4-4b3f-a639-c76fbd639a32,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,304,M2,303-M2-76,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,303,304

In [54]:
list(df_all_cars['carId']).index('aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7')

102

In [55]:
data_car3 = load_api('https://corners.synology.me:30006/woojin-dev490/WorkPlan/' + project_id + '/' + df_all_cars['carId'][102])
df_car3 = pd.DataFrame(data_car3['data'])
df_car3

,projId,pcId,planDate,pcnt,cno1,cno2,cno3,pcNm
0,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,c95df008-e3f6-4d55-9325-8e76da5fc734,2021-04-19,167,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,UNDER PANEL 조립 & 검사 & 자동용접
1,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,8fd9915f-40b7-40f6-9c5f-b8b09dc0637b,2021-04-20,167,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,UNDER PANEL 가공
2,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,75dbd449-84cb-4b01-912c-9534a82dba86,2021-05-17,167,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,UNDER SIDE SILL 조립 & 자동용접
3,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,87cfd948-e4c6-4fe9-ad7b-7efb6cf50dab,2021-05-18,167,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,UNDER PANEL 팽창폼 삽입
4,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f5032bdb-3465-42d1-828e-dc8aa2980c06,2021-06-23,167,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,UNDER/END/SIDE/ROOF 조립
...,...,...,...,...,...,...,...,...
69,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b6cd7eb1-2faa-4127-a457-8744facf75d7,2021-11-01,190,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,전장품 취부 입회검사
70,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,2021-11-01,190,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,수정작업 및 점검커버 복구 (의장)
71,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,118546fb-155d-4fd4-b716-334ac5602428,2021-11-02,191,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,대차차입 전 검사 / 대차 차입
72,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,cfae0823-3d36-4f38-a902-619beca12b22,2021-11-02,191,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,대차차입 후 검사
73,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2a2f3901-14cb-45b4-b17a-d12a569790ea,2021-11-02,191,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,대차측 전장품 취부 결선 및 마무리작업

In [56]:
data_car4 = load_api('https://corners.synology.me:30006/woojin-dev490/WorkPlan/' + project_id + '/' + df_all_cars['carId'][list(df_all_cars['carId']).index('3d6d8274-ef61-4910-bf9c-1ed6919b6b95')])
df_car4 = pd.DataFrame(data_car4['data'])
df_car4

,projId,pcId,planDate,pcnt,cno1,cno2,cno3,pcNm
0,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,c95df008-e3f6-4d55-9325-8e76da5fc734,2021-04-16,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,UNDER PANEL 조립 & 검사 & 자동용접
1,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,8fd9915f-40b7-40f6-9c5f-b8b09dc0637b,2021-04-17,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,UNDER PANEL 가공
2,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,75dbd449-84cb-4b01-912c-9534a82dba86,2021-05-14,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,UNDER SIDE SILL 조립 & 자동용접
3,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,87cfd948-e4c6-4fe9-ad7b-7efb6cf50dab,2021-05-17,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,UNDER PANEL 팽창폼 삽입
4,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f5032bdb-3465-42d1-828e-dc8aa2980c06,2021-06-23,167,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,UNDER/END/SIDE/ROOF 조립
...,...,...,...,...,...,...,...,...
66,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,cfae0823-3d36-4f38-a902-619beca12b22,2021-10-19,179,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,대차차입 후 검사
67,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2a2f3901-14cb-45b4-b17a-d12a569790ea,2021-10-19,179,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,대차측 전장품 취부 결선 및 마무리작업
68,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,118546fb-155d-4fd4-b716-334ac5602428,2021-11-01,190,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,대차차입 전 검사 / 대차 차입
69,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2a2f3901-14cb-45b4-b17a-d12a569790ea,2021-11-01,190,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,대차측 전장품 취부 결선 및 마무리작업
70,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,cfae0823-3d36-4f38-a902-619beca12b22,2021-11-01,190,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,대차차입 후 검사

In [57]:
df_car3[df_car3['pcId'].isin(df_proc4['pcId'])]

,projId,pcId,planDate,pcnt,cno1,cno2,cno3,pcNm
25,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,8718b46d-cf23-4b2f-959c-c1a63f9532b6,2021-08-26,168,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,흡음재 취부
26,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,c30eb0bd-a767-409a-a968-75aa0757bfb0,2021-08-27,168,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,흡음재 취부 검사
27,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f3b9bd9d-eba6-4fa5-98fb-3202fe0b5f1b,2021-08-28,168,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,"상,하 하네스 덕트 취부"
28,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,803d1d3c-6efd-4a42-bfbf-cccb4868bbfd,2021-08-30,168,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,실내/상하 배선
29,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727,2021-09-02,169,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,실내/상하 입선 검사/수정
30,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,612897d8-78df-4b88-bcc0-b4e1d942a1c2,2021-09-06,170,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,STOP PLATE & 센터그릴 취부
31,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3f69f52d-c206-43a5-abd1-d47eb8e8aabf,2021-09-06,170,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,LINE FLOW FAN 취부
32,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f1441ccb-398b-46fd-b9e8-128c5fa49bb2,2021-09-07,170,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,AIR DUCT MODULE 취부 검사
33,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,7dac19ab-a4d8-431f-95a9-199e3dbaa684,2021-09-08,169,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,배관 모듈 취부
34,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,239fddf2-c250-4761-a14f-2a941a9fda75,2021-09-09,169,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,ROOF 내장판 취부
35,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,27f617fd-d1b3-4175-bb84-f24c848d3090,2021-09-10,148,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,CENTER PIVOT 취부
36,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,aa77dbb8-fa64-403f-9e40-f4a1b398b7bf,2021-09-11,169,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,제동기기 취부 및 누설검사
37,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,fce31937-b674-4400-8ceb-776864a641ed,2021-09-11,169,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,COUPLER 취부
38,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e,2021-09-13,151,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,냉난방 배전반 취부
39,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,406990fb-253f-4b65-a7db-c7e50f6775cb,2021-09-25,173,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,객실도어 취부 검사
40,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,6b0dcc6c-9fea-42c5-947c-6815ba40370b,2021-09-25,176,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,객실 도어 취부
41,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,afcd8387-dc68-4d2e-8068-d1e01e619e89,2021-09-29,178,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,SIDE 내장판 취부
42,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2021-09-30,176,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,상하 전장기기 취부 결선
43,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2f14336a-38e5-4650-ab56-b8045fac5be0,2021-09-30,176,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,옥상 기기 취부 및 결선
44,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,6b0dcc6c-9fea-42c5-947c-6815ba40370b,2021-10-01,182,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,객실 도어 취부
45,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,406990fb-253f-4b65-a7db-c7e50f6775cb,2021-10-02,178,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,객실도어 취부 검사
46,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e,2021-10-04,165,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,냉난방 배전반 취부
47,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2f14336a-38e5-4650-ab56-b8045fac5be0,2021-10-06,181,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,옥상 기기 취부 및 결선
48,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,afcd8387-dc68-4d2e-8068-d1e01e619e89,2021-10-06,184,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,SIDE 내장판 취부
49,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2021-10-06,181,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,상하 전장기기 취부 결선
50,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,127fdb1e-97fd-4525-a4c2-05dd123dff8b,2021-10-07,167,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,부적합수정
51,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3d3a7a3e-2326-40e5-b810-e98df91b745d,2021-10-07,167,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,도통 검사
52,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,9184fc1e-f9f5-4dd6-b2f5-e942b9613b27,2021-10-08,165,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,도통입회검사/내전압자체검사
53,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,95b44996-4c78-4d27-808c-8c457ce76be8,2021-10-09,158,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,내전압 입회검사
54,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,002cfaa5-4bf1-4325-9d54-281b9e4f439e,2021-10-14,183,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,내장판 조정작업
55,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,d1e83483-4e9b-4b1a-beba-9a8994d06528,2021-10-15,182,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,내장판 취부 검사
56,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,59043214-e767-4ba2-8992-754b68dfebea,2021-10-16,37,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,전장기기 취부 결선 완료
57,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,19eade95-30e7-41f4-ba1f-e09e09614c4a,2021-10-19,188,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,에어컨 취부
58,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,07cda3b6-bee6-4b16-a2fa-3a6b02a50689,2021-10-19,182,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,전장취부 결선 복구
59,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,9a6519e5-8bd2-443e-8bd0-e3787716fe7d,2021-10-19,182,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,실내 조정 및 Sealing 작업
60,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,793cf042-2a6d-409b-a7a6-38cca3701aa0,2021-10-21,181,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,수정작업 및 점검커버 복구 (전기)
61,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,2021-10-21,181,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,실내 설비 입회검사
62,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b6cd7eb1-2faa-4127-a457-8744facf75d7,2021-10-21,181,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,전장품 취부 입회검사
63,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,2021-10-21,181,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,수정작업 및 점검커버 복구 (의장)
67,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,2021-11-01,190,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,실내 설비 입회검사
68,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,793cf042-2a6d-409b-a7a6-38cca3701aa0,2021-11-01,190,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,수정작업 및 점검커버 복구 (전기)
69,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b6cd7eb1-2faa-4127-a457-8744facf75d7,2021-11-01,190,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,전장품 취부 입회검사
70,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,2021-11-01,190,aed83c1b-aac3-4c5d-9af2-2d1f1c032ce7,None,None,수정작업 및 점검커버 복구 (의장)

In [58]:
df_car4[df_car4['pcId'].isin(df_proc4['pcId'])]

,projId,pcId,planDate,pcnt,cno1,cno2,cno3,pcNm
25,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,8718b46d-cf23-4b2f-959c-c1a63f9532b6,2021-08-24,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,흡음재 취부
26,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,c30eb0bd-a767-409a-a968-75aa0757bfb0,2021-08-25,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,흡음재 취부 검사
27,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f3b9bd9d-eba6-4fa5-98fb-3202fe0b5f1b,2021-08-26,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,"상,하 하네스 덕트 취부"
28,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,803d1d3c-6efd-4a42-bfbf-cccb4868bbfd,2021-08-27,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,실내/상하 배선
29,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,51eab8d3-38d2-453b-962e-6f16e0ffa081,2021-08-30,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,리무벌프레임 취부
30,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727,2021-08-30,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,실내/상하 입선 검사/수정
31,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b1d76e32-b363-49ed-9d1e-df5fe4699ed1,2021-08-31,166,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,에어 덕트 취부
32,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f1441ccb-398b-46fd-b9e8-128c5fa49bb2,2021-09-01,165,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,AIR DUCT MODULE 취부 검사
33,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727,2021-09-01,168,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,실내/상하 입선 검사/수정
34,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,239fddf2-c250-4761-a14f-2a941a9fda75,2021-09-07,167,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,ROOF 내장판 취부
35,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,7dac19ab-a4d8-431f-95a9-199e3dbaa684,2021-09-07,168,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,배관 모듈 취부
36,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,27f617fd-d1b3-4175-bb84-f24c848d3090,2021-09-09,147,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,CENTER PIVOT 취부
37,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,fce31937-b674-4400-8ceb-776864a641ed,2021-09-10,168,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,COUPLER 취부
38,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e,2021-09-10,149,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,냉난방 배전반 취부
39,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,aa77dbb8-fa64-403f-9e40-f4a1b398b7bf,2021-09-10,168,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,제동기기 취부 및 누설검사
40,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,6b0dcc6c-9fea-42c5-947c-6815ba40370b,2021-09-24,175,da2aaa7f-987e-46d8-bad7-e062eed05f66,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,객실 도어 취부
41,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,406990fb-253f-4b65-a7db-c7e50f6775cb,2021-09-24,172,da2aaa7f-987e-46d8-bad7-e062eed05f66,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,객실도어 취부 검사
42,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,afcd8387-dc68-4d2e-8068-d1e01e619e89,2021-09-28,177,da2aaa7f-987e-46d8-bad7-e062eed05f66,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,SIDE 내장판 취부
43,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2021-09-29,175,da2aaa7f-987e-46d8-bad7-e062eed05f66,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,상하 전장기기 취부 결선
44,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2f14336a-38e5-4650-ab56-b8045fac5be0,2021-09-29,175,da2aaa7f-987e-46d8-bad7-e062eed05f66,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,옥상 기기 취부 및 결선
45,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,127fdb1e-97fd-4525-a4c2-05dd123dff8b,2021-09-30,163,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,부적합수정
46,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,19eade95-30e7-41f4-ba1f-e09e09614c4a,2021-09-30,174,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,에어컨 취부
47,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3d3a7a3e-2326-40e5-b810-e98df91b745d,2021-09-30,163,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,도통 검사
48,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,afcd8387-dc68-4d2e-8068-d1e01e619e89,2021-10-01,181,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,SIDE 내장판 취부
49,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2f14336a-38e5-4650-ab56-b8045fac5be0,2021-10-02,178,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,옥상 기기 취부 및 결선
50,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2021-10-02,178,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,상하 전장기기 취부 결선
51,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,127fdb1e-97fd-4525-a4c2-05dd123dff8b,2021-10-04,165,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,부적합수정
52,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3d3a7a3e-2326-40e5-b810-e98df91b745d,2021-10-04,165,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,도통 검사
53,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,9184fc1e-f9f5-4dd6-b2f5-e942b9613b27,2021-10-05,163,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,도통입회검사/내전압자체검사
54,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,95b44996-4c78-4d27-808c-8c457ce76be8,2021-10-06,156,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,내전압 입회검사
55,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,002cfaa5-4bf1-4325-9d54-281b9e4f439e,2021-10-11,180,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,내장판 조정작업
56,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,d1e83483-4e9b-4b1a-beba-9a8994d06528,2021-10-12,179,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,내장판 취부 검사
57,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,59043214-e767-4ba2-8992-754b68dfebea,2021-10-13,34,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,전장기기 취부 결선 완료
58,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,9a6519e5-8bd2-443e-8bd0-e3787716fe7d,2021-10-15,179,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,실내 조정 및 Sealing 작업
59,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,07cda3b6-bee6-4b16-a2fa-3a6b02a50689,2021-10-15,179,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,전장취부 결선 복구
60,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,19eade95-30e7-41f4-ba1f-e09e09614c4a,2021-10-15,185,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,에어컨 취부
61,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,793cf042-2a6d-409b-a7a6-38cca3701aa0,2021-10-18,178,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,수정작업 및 점검커버 복구 (전기)
62,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,2021-10-18,178,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,수정작업 및 점검커버 복구 (의장)
63,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b6cd7eb1-2faa-4127-a457-8744facf75d7,2021-10-18,178,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,전장품 취부 입회검사
64,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,2021-10-18,178,3d6d8274-ef61-4910-bf9c-1ed6919b6b95,None,None,실내 설비 입회검사

In [59]:
df_proc4

,pcDaySeq,pcId,pcTp,pcCd,pcNm,tcCheck,m1Check,examCheck,lastPcYn
0,1,8718b46d-cf23-4b2f-959c-c1a63f9532b6,1,PROC0004,흡음재 취부,0,0,0,N
1,2,c30eb0bd-a767-409a-a968-75aa0757bfb0,1,PROC0004,흡음재 씰링/검사/수정,0,0,1,N
2,3,f3b9bd9d-eba6-4fa5-98fb-3202fe0b5f1b,2,PROC0004,실내/상하 CABLE HARNESS 취부,0,0,0,N
3,4,803d1d3c-6efd-4a42-bfbf-cccb4868bbfd,2,PROC0004,실내/상하 배선,0,0,0,N
4,5,e0471187-5ee5-4fed-8383-c102704e26df,2,PROC0004,D+1~4일차 조정작업,0,0,1,N
5,6,51eab8d3-38d2-453b-962e-6f16e0ffa081,1,PROC0004,리무벌프레임 취부,0,0,0,N
6,6,0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727,2,PROC0004,실내/상하 입선 검사/수정,0,0,1,N
7,7,b1d76e32-b363-49ed-9d1e-df5fe4699ed1,1,PROC0004,AIR DUCT MODULE 취부,0,0,0,N
8,8,93d2cc2b-a71f-40c0-ae8d-0d2af8885f9c,1,PROC0004,측창취부,0,0,0,N
9,8,3f69f52d-c206-43a5-abd1-d47eb8e8aabf,2,PROC0004,LINE FLOW FAN 취부 결선,0,0,0,N
10,8,612897d8-78df-4b88-bcc0-b4e1d942a1c2,1,PROC0004,STOP PLATE & 센터그릴 취부,0,0,0,N
11,9,04dbb438-9874-4cb3-ba23-48dba6b6aab7,1,PROC0004,CAB MODULE 취부,1,0,0,N
12,9,f1441ccb-398b-46fd-b9e8-128c5fa49bb2,1,PROC0004,AIR DUCT MODULE 취부 검사,0,0,1,N
13,9,19eade95-30e7-41f4-ba1f-e09e09614c4a,3,PROC0004,AIR CON 취부,0,0,0,N
14,10,239fddf2-c250-4761-a14f-2a941a9fda75,1,PROC0004,ROOF 내장판 취부,0,0,0,N
15,10,fdb5af99-eac4-4ece-9f42-0c6639fdce5c,1,PROC0004,운전실 내장판/캐비넷 취부,1,0,0,N
16,11,7dac19ab-a4d8-431f-95a9-199e3dbaa684,3,PROC0004,배관 MODULE 취부,0,0,0,N
17,11,6b0dcc6c-9fea-42c5-947c-6815ba40370b,1,PROC0004,객실 도어 취부,0,0,0,N
18,12,406990fb-253f-4b65-a7db-c7e50f6775cb,1,PROC0004,객실도어 취부 검사,0,0,1,N
19,13,27f617fd-d1b3-4175-bb84-f24c848d3090,3,PROC0004,CENTER PIVOT 취부,0,0,0,N
20,13,ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e,2,PROC0004,"일반,냉난방 배전반 취부 결선",0,0,0,N
21,14,aa77dbb8-fa64-403f-9e40-f4a1b398b7bf,3,PROC0004,제동기기 취부 및 누설검사,0,0,1,Y
22,14,fce31937-b674-4400-8ceb-776864a641ed,3,PROC0004,COUPLER 취부,0,0,0,N
23,15,afcd8387-dc68-4d2e-8068-d1e01e619e89,1,PROC0004,SIDE 내장판 취부,0,0,0,N
24,16,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2,PROC0004,상하 전장기기 취부 결선,0,0,0,N
25,16,2f14336a-38e5-4650-ab56-b8045fac5be0,2,PROC0004,옥상기기 취부 결선,0,0,0,N
26,17,3d3a7a3e-2326-40e5-b810-e98df91b745d,2,PROC0004,도통 검사,0,0,1,N
27,18,9184fc1e-f9f5-4dd6-b2f5-e942b9613b27,2,PROC0004,도통입회검사/내전압자체검사,0,0,1,N
28,18,127fdb1e-97fd-4525-a4c2-05dd123dff8b,2,PROC0004,부적합수정,0,0,0,N
29,19,95b44996-4c78-4d27-808c-8c457ce76be8,2,PROC0004,내전압 입회검사,0,0,1,N
30,20,30238e8d-aa85-40d0-b621-578ed1d9bd00,2,PROC0004,D+5~16일차 조정작업,0,0,1,N
31,21,67114600-1c26-4313-941b-10c2e4d6a1ff,2,PROC0004,운전실 배전반 취부 결선,1,0,0,N
32,22,c49e416e-39de-48d6-815a-4ee0e734015b,1,PROC0004,운전실 DOOR 취부,1,0,0,N
33,23,0a1ebad7-306b-4f6d-87f1-6adb7bc1d0cd,2,PROC0004,운전실 전장기기 취부 결선,1,0,0,N
34,23,002cfaa5-4bf1-4325-9d54-281b9e4f439e,1,PROC0004,내장판 조정작업(완료),0,0,0,N
35,24,d1e83483-4e9b-4b1a-beba-9a8994d06528,1,PROC0004,내장판 취부 검사,0,0,1,N
36,25,59043214-e767-4ba2-8992-754b68dfebea,2,PROC0004,전장기기 취부 결선 완료,0,0,0,N
37,25,347041ed-ed49-4175-8391-6dd284b4e637,2,PROC0004,도통 자체 검사 (TC-Car),1,0,0,N
38,26,7a21a47f-fea2-4c33-a991-c9fbe85eec90,2,PROC0004,도통 검사 수정 (TC-Car),1,0,0,N
39,27,07cda3b6-bee6-4b16-a2fa-3a6b02a50689,2,PROC0004,전장취부 결선 복구,0,0,0,N
40,27,9a6519e5-8bd2-443e-8bd0-e3787716fe7d,1,PROC0004,실내조정 및 Sealing,0,0,0,N
41,27,9cda7382-f0bd-4b0a-908d-82d5c83fb0c4,2,PROC0004,"도통,내전압 검사 (TC-Car)",1,0,1,N
42,28,f12e681f-1f2a-46b1-819c-c22d580a0a3b,2,PROC0004,D+17~20일차 조정작업,0,0,1,N
43,28,ef4ef3c1-5598-4f99-bd0d-b45bf186a3aa,2,PROC0004,내전압 입회 검사 (TC-Car),1,0,0,N
44,29,b6cd7eb1-2faa-4127-a457-8744facf75d7,2,PROC0004,전장품 취부 입회검사,0,0,1,N
45,29,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,1,PROC0004,수정작업 및 점검커버 복구 (의장),0,0,0,N
46,29,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,1,PROC0004,실내 설비 입회검사,0,0,1,Y
47,29,793cf042-2a6d-409b-a7a6-38cca3701aa0,2,PROC0004,수정작업 및 점검커버 복구 (전기),0,0,0,N

In [60]:
pd.to_datetime(df_car4['planDate'][0])

Timestamp('2021-04-16 00:00:00')

In [8]:
data_proc = load_api('https://corners.synology.me:30006/woojin-dev490/Processes/Seq')
df_proc = pd.DataFrame(data_proc['data'])
df_proc = df_proc[(df_proc['pcCd']=='PROC0004')| (df_proc['pcCd']=='PROC0005')]

In [13]:
df_proc

,pcDaySeq,pcId,pcTp,pcCd,pcNm,tcCheck,m1Check,examCheck,lastPcYn
9,1,8718b46d-cf23-4b2f-959c-c1a63f9532b6,1,PROC0004,흡음재 취부,0,0,0,N
10,2,c30eb0bd-a767-409a-a968-75aa0757bfb0,1,PROC0004,흡음재 씰링/검사/수정,0,0,1,N
11,3,f3b9bd9d-eba6-4fa5-98fb-3202fe0b5f1b,2,PROC0004,실내/상하 CABLE HARNESS 취부,0,0,0,N
12,4,803d1d3c-6efd-4a42-bfbf-cccb4868bbfd,2,PROC0004,실내/상하 배선,0,0,0,N
13,5,e0471187-5ee5-4fed-8383-c102704e26df,2,PROC0004,D+1~4일차 조정작업,0,0,1,N
14,6,0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727,2,PROC0004,실내/상하 입선 검사/수정,0,0,1,N
15,6,51eab8d3-38d2-453b-962e-6f16e0ffa081,1,PROC0004,리무벌프레임 취부,0,0,0,N
16,7,b1d76e32-b363-49ed-9d1e-df5fe4699ed1,1,PROC0004,AIR DUCT MODULE 취부,0,0,0,N
17,8,93d2cc2b-a71f-40c0-ae8d-0d2af8885f9c,1,PROC0004,측창취부,0,0,0,N
18,8,612897d8-78df-4b88-bcc0-b4e1d942a1c2,1,PROC0004,STOP PLATE & 센터그릴 취부,0,0,0,N
19,8,3f69f52d-c206-43a5-abd1-d47eb8e8aabf,2,PROC0004,LINE FLOW FAN 취부 결선,0,0,0,N
20,9,19eade95-30e7-41f4-ba1f-e09e09614c4a,3,PROC0004,AIR CON 취부,0,0,0,N
21,9,f1441ccb-398b-46fd-b9e8-128c5fa49bb2,1,PROC0004,AIR DUCT MODULE 취부 검사,0,0,1,N
22,9,04dbb438-9874-4cb3-ba23-48dba6b6aab7,1,PROC0004,CAB MODULE 취부,1,0,0,N
23,10,fdb5af99-eac4-4ece-9f42-0c6639fdce5c,1,PROC0004,운전실 내장판/캐비넷 취부,1,0,0,N
24,10,239fddf2-c250-4761-a14f-2a941a9fda75,1,PROC0004,ROOF 내장판 취부,0,0,0,N
25,11,6b0dcc6c-9fea-42c5-947c-6815ba40370b,1,PROC0004,객실 도어 취부,0,0,0,N
26,11,7dac19ab-a4d8-431f-95a9-199e3dbaa684,3,PROC0004,배관 MODULE 취부,0,0,0,N
27,12,406990fb-253f-4b65-a7db-c7e50f6775cb,1,PROC0004,객실도어 취부 검사,0,0,1,N
28,13,27f617fd-d1b3-4175-bb84-f24c848d3090,3,PROC0004,CENTER PIVOT 취부,0,0,0,N
29,13,ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e,2,PROC0004,"일반,냉난방 배전반 취부 결선",0,0,0,N
30,14,aa77dbb8-fa64-403f-9e40-f4a1b398b7bf,3,PROC0004,제동기기 취부 및 누설검사,0,0,1,Y
31,14,fce31937-b674-4400-8ceb-776864a641ed,3,PROC0004,COUPLER 취부,0,0,0,N
32,15,afcd8387-dc68-4d2e-8068-d1e01e619e89,1,PROC0004,SIDE 내장판 취부,0,0,0,N
33,16,2f14336a-38e5-4650-ab56-b8045fac5be0,2,PROC0004,옥상기기 취부 결선,0,0,0,N
34,16,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2,PROC0004,상하 전장기기 취부 결선,0,0,0,N
35,17,3d3a7a3e-2326-40e5-b810-e98df91b745d,2,PROC0004,도통 검사,0,0,1,N
36,18,127fdb1e-97fd-4525-a4c2-05dd123dff8b,2,PROC0004,부적합수정,0,0,0,N
37,18,9184fc1e-f9f5-4dd6-b2f5-e942b9613b27,2,PROC0004,도통입회검사/내전압자체검사,0,0,1,N
38,19,95b44996-4c78-4d27-808c-8c457ce76be8,2,PROC0004,내전압 입회검사,0,0,1,N
39,20,30238e8d-aa85-40d0-b621-578ed1d9bd00,2,PROC0004,D+5~16일차 조정작업,0,0,1,N
40,21,67114600-1c26-4313-941b-10c2e4d6a1ff,2,PROC0004,운전실 배전반 취부 결선,1,0,0,N
41,22,c49e416e-39de-48d6-815a-4ee0e734015b,1,PROC0004,운전실 DOOR 취부,1,0,0,N
42,23,002cfaa5-4bf1-4325-9d54-281b9e4f439e,1,PROC0004,내장판 조정작업(완료),0,0,0,N
43,23,0a1ebad7-306b-4f6d-87f1-6adb7bc1d0cd,2,PROC0004,운전실 전장기기 취부 결선,1,0,0,N
44,24,d1e83483-4e9b-4b1a-beba-9a8994d06528,1,PROC0004,내장판 취부 검사,0,0,1,N
45,25,59043214-e767-4ba2-8992-754b68dfebea,2,PROC0004,전장기기 취부 결선 완료,0,0,0,N
46,25,347041ed-ed49-4175-8391-6dd284b4e637,2,PROC0004,도통 자체 검사 (TC-Car),1,0,0,N
47,26,7a21a47f-fea2-4c33-a991-c9fbe85eec90,2,PROC0004,도통 검사 수정 (TC-Car),1,0,0,N
48,27,9cda7382-f0bd-4b0a-908d-82d5c83fb0c4,2,PROC0004,"도통,내전압 검사 (TC-Car)",1,0,1,N
49,27,07cda3b6-bee6-4b16-a2fa-3a6b02a50689,2,PROC0004,전장취부 결선 복구,0,0,0,N
50,27,9a6519e5-8bd2-443e-8bd0-e3787716fe7d,1,PROC0004,실내조정 및 Sealing,0,0,0,N
51,28,f12e681f-1f2a-46b1-819c-c22d580a0a3b,2,PROC0004,D+17~20일차 조정작업,0,0,1,N
52,28,ef4ef3c1-5598-4f99-bd0d-b45bf186a3aa,2,PROC0004,내전압 입회 검사 (TC-Car),1,0,0,N
53,29,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,1,PROC0004,수정작업 및 점검커버 복구 (의장),0,0,0,N
54,29,793cf042-2a6d-409b-a7a6-38cca3701aa0,2,PROC0004,수정작업 및 점검커버 복구 (전기),0,0,0,N
55,29,b6cd7eb1-2faa-4127-a457-8744facf75d7,2,PROC0004,전장품 취부 입회검사,0,0,1,N
56,29,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,1,PROC0004,실내 설비 입회검사,0,0,1,Y
57,1,cfae0823-3d36-4f38-a902-619beca12b22,6,PROC0005,대차차입 후 검사,0,0,1,Y
58,1,2a2f3901-14cb-45b4-b17a-d12a569790ea,6,PROC0005,대차측 전장품 취부 결선 및 마무리작업,0,0,0,N
59,1,118546fb-155d-4fd4-b716-334ac5602428,6,PROC0005,대차차입 전 검사 / 대차 차입,0,0,1,N

In [12]:
df_proc[df_proc['pcId'] == 'cfae0823-3d36-4f38-a902-619beca12b22']

,pcDaySeq,pcId,pcTp,pcCd,pcNm,tcCheck,m1Check,examCheck,lastPcYn
57,1,cfae0823-3d36-4f38-a902-619beca12b22,6,PROC0005,대차차입 후 검사,0,0,1,Y

In [17]:
start_date = pd.to_datetime('2021-08-01')
end_date = pd.to_datetime('2021-10-31')

In [18]:
data_dict = dict()
for car_id in list(df_all_cars['carId']):
    data_temp = load_api('https://corners.synology.me:30006/woojin-dev490/WorkPlan/' + project_id + '/' + car_id)
    if data_temp['code'] == 10:
        continue
    df_temp = pd.DataFrame(data_temp['data'])
    df_temp = df_temp[pd.to_datetime(df_temp['planDate']) >= start_date]
    df_temp = df_temp[pd.to_datetime(df_temp['planDate']) <= end_date]
    df_temp = df_temp[df_temp['pcId'].isin(df_proc['pcId'])]
    if df_temp.shape[0] == 0:
        continue
    data_dict[car_id] = df_temp
    break

In [22]:
df_temp

,projId,pcId,planDate,pcnt,cno1,cno2,cno3,pcNm
51,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,실내 설비 입회검사
52,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,수정작업 및 점검커버 복구 (의장)
53,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b6cd7eb1-2faa-4127-a457-8744facf75d7,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,전장품 취부 입회검사
54,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,793cf042-2a6d-409b-a7a6-38cca3701aa0,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,수정작업 및 점검커버 복구 (전기)
55,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,118546fb-155d-4fd4-b716-334ac5602428,2021-08-05,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,대차차입 전 검사 / 대차 차입
56,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2a2f3901-14cb-45b4-b17a-d12a569790ea,2021-08-05,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,대차측 전장품 취부 결선 및 마무리작업
57,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,cfae0823-3d36-4f38-a902-619beca12b22,2021-08-05,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,대차차입 후 검사

In [19]:
data_dict[data_dict.keys()[0]]

TypeError: 'dict_keys' object is not subscriptable

In [88]:
len(data_dict.values())

90

In [91]:
list(data_dict.values())[0]

,projId,pcId,planDate,pcnt,cno1,cno2,cno3,pcNm
51,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,실내 설비 입회검사
52,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,수정작업 및 점검커버 복구 (의장)
53,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,b6cd7eb1-2faa-4127-a457-8744facf75d7,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,전장품 취부 입회검사
54,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,793cf042-2a6d-409b-a7a6-38cca3701aa0,2021-08-04,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,수정작업 및 점검커버 복구 (전기)
55,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,118546fb-155d-4fd4-b716-334ac5602428,2021-08-05,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,대차차입 전 검사 / 대차 차입
56,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2a2f3901-14cb-45b4-b17a-d12a569790ea,2021-08-05,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,대차측 전장품 취부 결선 및 마무리작업
57,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,cfae0823-3d36-4f38-a902-619beca12b22,2021-08-05,118,860c494a-be34-4a7e-b5e6-1e1b046371e3,None,None,대차차입 후 검사

In [96]:
for car_id, df_car in data_dict.items():
    print(df_all_cars[df_all_cars['carId'] == car_id]['carSeq'].values[0])

104
113
120
129
130
131
132
133
134
135
136
145
146
147
148
149
150
151
152
161
162
163
164
165
166
167
168
177
178
179
180
181
182
183
184
193
194
195
196
197
198
199
200
105
112
121
122
123
124
125
126
127
128
137
138
139
140
141
142
143
144
153
154
155
156
157
158
159
160
169
170
171
172
173
174
175
176
185
186
187
188
189
190
191
192
201
203
204
205
206

In [93]:
df_all_cars

,carId,projId,carSeq,carType,carCd,carPairNo,lineNo,progress,latency,totalTime,...,useNextYn,planCarYn,prevPlanDate,firstPlanDate,firstChkDay,lastPlanDate,lastPcId,lastChkDay,carNo,carSeqS
0,eaf6f703-18c4-4d64-9d96-09cbe521b98d,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,1,TC1,001-TC1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,001,1
1,fcdd791d-d9ce-4191-9451-9738c13d9978,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,2,M1,002-M1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,002,2
2,9462c71b-52aa-4df6-84b4-a8fcbf2094fb,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,3,M2,003-M2-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,003,3
3,907a3d1d-1ec6-4e05-9129-aec5082aa9d3,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,4,TC2,008-TC2-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,008,4
4,8eae2965-e109-49c8-8e2e-bcd38d5d579f,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,5,T1,004-T1-01,501,5,100,0,43022,...,None,None,None,None,None,None,None,None,004,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,68134945-224e-4ba8-96ec-0335e940aa13,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,300,M2,299-M2-75,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,299,300
332,3d6fae33-bef3-4a62-970c-df564d3a1087,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,301,T2,301-T2-38,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,301,301
333,675993ce-07bc-4eb7-94c7-2732d432be49,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,302,M1,302-M1-76,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,302,302
334,5281ee51-27d4-4f8f-85bf-2ba5e1b7d995,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,303,TC2,304-TC2-38,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,304,303
335,50f3de2c-23d4-4b3f-a639-c76fbd639a32,e672bd1e-5ed0-4baa-9cbd-50db20ea24db,304,M2,303-M2-76,717,7,100,0,43022,...,None,None,None,None,None,None,None,None,303,304

In [99]:
df_proc

,pcDaySeq,pcId,pcTp,pcCd,pcNm,tcCheck,m1Check,examCheck,lastPcYn
9,1,8718b46d-cf23-4b2f-959c-c1a63f9532b6,1,PROC0004,흡음재 취부,0,0,0,N
10,2,c30eb0bd-a767-409a-a968-75aa0757bfb0,1,PROC0004,흡음재 씰링/검사/수정,0,0,1,N
11,3,f3b9bd9d-eba6-4fa5-98fb-3202fe0b5f1b,2,PROC0004,실내/상하 CABLE HARNESS 취부,0,0,0,N
12,4,803d1d3c-6efd-4a42-bfbf-cccb4868bbfd,2,PROC0004,실내/상하 배선,0,0,0,N
13,5,e0471187-5ee5-4fed-8383-c102704e26df,2,PROC0004,D+1~4일차 조정작업,0,0,1,N
14,6,0c210f4c-8d06-4d56-b0ee-e5f5c2fc3727,2,PROC0004,실내/상하 입선 검사/수정,0,0,1,N
15,6,51eab8d3-38d2-453b-962e-6f16e0ffa081,1,PROC0004,리무벌프레임 취부,0,0,0,N
16,7,b1d76e32-b363-49ed-9d1e-df5fe4699ed1,1,PROC0004,AIR DUCT MODULE 취부,0,0,0,N
17,8,93d2cc2b-a71f-40c0-ae8d-0d2af8885f9c,1,PROC0004,측창취부,0,0,0,N
18,8,612897d8-78df-4b88-bcc0-b4e1d942a1c2,1,PROC0004,STOP PLATE & 센터그릴 취부,0,0,0,N
19,8,3f69f52d-c206-43a5-abd1-d47eb8e8aabf,2,PROC0004,LINE FLOW FAN 취부 결선,0,0,0,N
20,9,19eade95-30e7-41f4-ba1f-e09e09614c4a,3,PROC0004,AIR CON 취부,0,0,0,N
21,9,f1441ccb-398b-46fd-b9e8-128c5fa49bb2,1,PROC0004,AIR DUCT MODULE 취부 검사,0,0,1,N
22,9,04dbb438-9874-4cb3-ba23-48dba6b6aab7,1,PROC0004,CAB MODULE 취부,1,0,0,N
23,10,fdb5af99-eac4-4ece-9f42-0c6639fdce5c,1,PROC0004,운전실 내장판/캐비넷 취부,1,0,0,N
24,10,239fddf2-c250-4761-a14f-2a941a9fda75,1,PROC0004,ROOF 내장판 취부,0,0,0,N
25,11,6b0dcc6c-9fea-42c5-947c-6815ba40370b,1,PROC0004,객실 도어 취부,0,0,0,N
26,11,7dac19ab-a4d8-431f-95a9-199e3dbaa684,3,PROC0004,배관 MODULE 취부,0,0,0,N
27,12,406990fb-253f-4b65-a7db-c7e50f6775cb,1,PROC0004,객실도어 취부 검사,0,0,1,N
28,13,27f617fd-d1b3-4175-bb84-f24c848d3090,3,PROC0004,CENTER PIVOT 취부,0,0,0,N
29,13,ec8c85a2-43d9-45b7-ae01-5bfba1cdd28e,2,PROC0004,"일반,냉난방 배전반 취부 결선",0,0,0,N
30,14,aa77dbb8-fa64-403f-9e40-f4a1b398b7bf,3,PROC0004,제동기기 취부 및 누설검사,0,0,1,Y
31,14,fce31937-b674-4400-8ceb-776864a641ed,3,PROC0004,COUPLER 취부,0,0,0,N
32,15,afcd8387-dc68-4d2e-8068-d1e01e619e89,1,PROC0004,SIDE 내장판 취부,0,0,0,N
33,16,2f14336a-38e5-4650-ab56-b8045fac5be0,2,PROC0004,옥상기기 취부 결선,0,0,0,N
34,16,ffe4e06d-cc13-472c-9bbf-7aceb852c0af,2,PROC0004,상하 전장기기 취부 결선,0,0,0,N
35,17,3d3a7a3e-2326-40e5-b810-e98df91b745d,2,PROC0004,도통 검사,0,0,1,N
36,18,127fdb1e-97fd-4525-a4c2-05dd123dff8b,2,PROC0004,부적합수정,0,0,0,N
37,18,9184fc1e-f9f5-4dd6-b2f5-e942b9613b27,2,PROC0004,도통입회검사/내전압자체검사,0,0,1,N
38,19,95b44996-4c78-4d27-808c-8c457ce76be8,2,PROC0004,내전압 입회검사,0,0,1,N
39,20,30238e8d-aa85-40d0-b621-578ed1d9bd00,2,PROC0004,D+5~16일차 조정작업,0,0,1,N
40,21,67114600-1c26-4313-941b-10c2e4d6a1ff,2,PROC0004,운전실 배전반 취부 결선,1,0,0,N
41,22,c49e416e-39de-48d6-815a-4ee0e734015b,1,PROC0004,운전실 DOOR 취부,1,0,0,N
42,23,002cfaa5-4bf1-4325-9d54-281b9e4f439e,1,PROC0004,내장판 조정작업(완료),0,0,0,N
43,23,0a1ebad7-306b-4f6d-87f1-6adb7bc1d0cd,2,PROC0004,운전실 전장기기 취부 결선,1,0,0,N
44,24,d1e83483-4e9b-4b1a-beba-9a8994d06528,1,PROC0004,내장판 취부 검사,0,0,1,N
45,25,59043214-e767-4ba2-8992-754b68dfebea,2,PROC0004,전장기기 취부 결선 완료,0,0,0,N
46,25,347041ed-ed49-4175-8391-6dd284b4e637,2,PROC0004,도통 자체 검사 (TC-Car),1,0,0,N
47,26,7a21a47f-fea2-4c33-a991-c9fbe85eec90,2,PROC0004,도통 검사 수정 (TC-Car),1,0,0,N
48,27,9cda7382-f0bd-4b0a-908d-82d5c83fb0c4,2,PROC0004,"도통,내전압 검사 (TC-Car)",1,0,1,N
49,27,07cda3b6-bee6-4b16-a2fa-3a6b02a50689,2,PROC0004,전장취부 결선 복구,0,0,0,N
50,27,9a6519e5-8bd2-443e-8bd0-e3787716fe7d,1,PROC0004,실내조정 및 Sealing,0,0,0,N
51,28,f12e681f-1f2a-46b1-819c-c22d580a0a3b,2,PROC0004,D+17~20일차 조정작업,0,0,1,N
52,28,ef4ef3c1-5598-4f99-bd0d-b45bf186a3aa,2,PROC0004,내전압 입회 검사 (TC-Car),1,0,0,N
53,29,1e3ab08b-af38-4c6a-9873-9fbf37f51e6c,1,PROC0004,수정작업 및 점검커버 복구 (의장),0,0,0,N
54,29,793cf042-2a6d-409b-a7a6-38cca3701aa0,2,PROC0004,수정작업 및 점검커버 복구 (전기),0,0,0,N
55,29,b6cd7eb1-2faa-4127-a457-8744facf75d7,2,PROC0004,전장품 취부 입회검사,0,0,1,N
56,29,f8c98cd0-4d74-4cea-8a88-8b9adb2fd07e,1,PROC0004,실내 설비 입회검사,0,0,1,Y
57,1,cfae0823-3d36-4f38-a902-619beca12b22,6,PROC0005,대차차입 후 검사,0,0,1,Y
58,1,2a2f3901-14cb-45b4-b17a-d12a569790ea,6,PROC0005,대차측 전장품 취부 결선 및 마무리작업,0,0,0,N
59,1,118546fb-155d-4fd4-b716-334ac5602428,6,PROC0005,대차차입 전 검사 / 대차 차입,0,0,1,N